# Generated by Django 4.2.16 on 2024-11-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discounted_price', models.CharField(max_length=50)),
                ('actual_price', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('product_url', models.URLField()),
            ],
        ),
    ]
